### ISSUE TITLE
mysql-container

### ISSUE THREAD

**Issue by rjtch** [renatof/evio_config_gen#4]
The newest Docker version does not support the user MYSQL_USER and work fine without it because it seems to create the root automatically.

--> https://stackoverflow.com/questions/66831863/mysql-docker-container-keeps-restarting

**Comment by renatof** [comment]
Thanks for bringing this up! To confirm, did you simply remove the MYSQL_USER entry from docker-compose.yml and it worked?

**Comment by rjtch** [comment]
No it doesn't work! In the Test1_turnadmin.sh file the password is not set correctly. The env variable is not used! I changed it and got the error that the connection is not secured. Docker has worked fine without the MYSQL_USER env variable

**Comment by renatof** [comment]
will have a look into it - if you find a solution to this, can you please do a pull request? thank you!

**Comment by rjtch** [comment]
Sure i will make a pull request with the my changes.
